# Site settings
title: Alexandru Litoiu
email: litoiu@gmail.com
description: "Alexandru Litoiu is a software engineer at Facebook using machine learning to keep users safe from fraudulent and offensive content."
baseurl: ""
url: "http://alitoiu.com"
twitter_username: alitoiu
goodreads_url: https://www.goodreads.com/review/list/9197254
linkedin_url: http://www.linkedin.com/pub/alex-litoiu/54/2a7/2
#bitbucket_username: alitoiu
#flickr_username: alitoiu

dropbox_url: https://www.dropbox.com/sh/fzu7at30fcly2iw/AADzsvKeZxV2-7Q_0XUeUANha/
#dropbox_url: http://googledrive.com/host/0B7ZfsJQwTv1Fb2QxbE1zS0JQYmc/

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

collections:
  projects:
    output: true

gems:
- jekyll-sitemap
