# Site settings
title: Alexandru Litoiu
email: litoiu@gmail.com
description: "Alexandru Litoiu is writing a book about his experiences and the importance of telling the truth."
baseurl: ""
url: "http://alitoiu.com"
twitter_username: alitoiu
goodreads_url: https://www.goodreads.com/review/list/9197254
linkedin_url: http://www.linkedin.com/pub/alex-litoiu/54/2a7/2
#bitbucket_username: alitoiu
#flickr_username: alitoiu

dropbox_url: http://alitoiu.com/static/ 
#dropbox_url: https://dl.dropboxusercontent.com/u/4354160/alitoiu/
#dropbox_url: http://googledrive.com/host/0B7ZfsJQwTv1Fb2QxbE1zS0JQYmc/

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

collections:
  projects:
    output: true

gems:
- jekyll-sitemap
