# Site settings
title: Alexandru Litoiu
email: litoiu@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://alitoiu.com"
twitter_username: alitoiu
github_username:  alitoiu

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

