# Site settings
title: Alexandru Litoiu
email: litoiu@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://alitoiu.com"
twitter_username: alitoiu
goodreads_url: https://www.goodreads.com/review/list/9197254
linkedin_url: http://www.linkedin.com/pub/alex-litoiu/54/2a7/2

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

collections:
  projects:
    output: true